version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    environment:
      - MONGO_DETAILS=mongodb://mongo:27017

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - fastapi


  mongo:
    image: mongo:4.2      # or the version you're using
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
